### ISSUE TITLE
Support Apple Accelerate

### ISSUE THREAD

**Issue by staticfloat** [staticfloat/libblastrampoline#16]
MacOS provides `Accelerate.framework`, which we can use to provide BLAS on MacOS and especially on apple silicon.  Unfortunately there seems to be some ABI differences specifically related to return codes on these libraries.  Since we want to provide the `gfortran`-compatible interface to all client code, we'll need to add some return code-altering shims and forward to those first, providing some small argument/return code massaging.

We should be able to auto-detect this similarly to how we auto-detect bitwidth; we can call an effected function (such as `sdot`) and look at the return code to see how the return codes are being passed back.

X-ref: https://github.com/tenomoto/dotwrp

**Comment by ViralBShah** [comment]
While this would be nice - I will note that Apple LAPACK is too old for Julia. Thus we have to compile LAPACK separately, and link against Accelerate. We still don't get all the nice multi-threaded LAPACK that other libraries like openblas and MKL have. 

It is still a good idea to be able to use Accelerate, especially on Apple silicon.

**Comment by simonbyrne** [comment]
It might be worth filing some bug reports with Apple:
https://twitter.com/stephentyrone/status/1293162645374349312?s=20

What LAPACK functions are multithreaded in OpenBLAS (as opposed to calling a multithreaded BLAS)?

**Comment by ViralBShah** [comment]
These ones: https://github.com/xianyi/OpenBLAS/tree/develop/lapack

MKL may do more (or not). It's hard to know.

**Comment by ViralBShah** [comment]
Where does one even report such a bug?

**Comment by staticfloat** [comment]
It would be good to get a simple benchmark script and run it on `x86_64` and `aarch64` doing a three-way comparison of BLAS/LAPACK on OpenBLAS, Accelerate and MKL (two-way on aarch64, obviously).

This is all so laughably easy now that we've got LBT, that it shouldn't take more than 10 minutes to write up the test suite with some appropriate `lbt_forward()` calls.

**Comment by ViralBShah** [comment]
First I have to get myself one of those M1 macs...

**Comment by staticfloat** [comment]
> First I have to get myself one of those M1 macs...

Unless you really want to be an early-adopter, I suggest holding off until we rebuild Yggdrasil.  We still don't have a great way to do that, so it's going to be a few months before things are truly smooth, I think.

**Comment by simonbyrne** [comment]
> Where does one even report such a bug?

I guess
https://developer.apple.com/bug-reporting/

**Comment by staticfloat** [comment]
Yeah, you file it all in [Feedback Assistant](https://feedbackassistant.apple.com/).  If you have something actionable, I can pass it to our developer liaison at Apple who seems to be doing a good job of passing it on to the relevant internal teams at Apple.
