### ISSUE TITLE
MKL specific symbols should not have the 64_ suffixes

### ISSUE THREAD

**Issue by ViralBShah** [staticfloat/libblastrampoline#20]
When we set up mangling to forward 64_ suffixes to MKL, the MKL APIs themselves should not have suffixes before forwarding.

So , while
`dgemm_64_` (LBT) -> `dgemm_` (MKL)

But
`MKL_Set_Interface_Layer` (LBT) -> `MKL_Set_Interface_Layer` (MKL)

**Comment by ViralBShah** [comment]
In the current setup, we get these forwards for MKL when on ILP64, which is the problem:

```
 - [4956] mkl_get_max_threads64_ -> mkl_get_max_threads [0x7f82514935c0]
 - [4957] mkl_get_max_threads_64_ -> mkl_get_max_threads_ [0x7f82514935c0]
 - [4958] MKL_Set_Num_Threads64_ -> MKL_Set_Num_Threads [0x7f8251494400]
 - [4960] MKL_Set_Interface_Layer64_ -> MKL_Set_Interface_Layer [0x7f82514953e0]
Processed 4962 symbols; forwarded 4774 symbols with 64-bit interface and mangling to a suffix of ""
```

**Comment by staticfloat** [comment]
Why is this a problem?

**Comment by ViralBShah** [comment]
Hmm. Probably not. I can just call these with the `64_` suffixes.
