### ISSUE TITLE
Which functions need to be re-entrant

### ISSUE THREAD

**Issue by ViralBShah** [staticfloat/libblastrampoline#28]
I wonder if we need locks to protect certain functions - or maybe just all.

**Comment by staticfloat** [comment]
I'm comfortable with simply saying that all functions starting with `lbt_` are thread-unsafe and that the client program should not call them on multiple threads.

**Comment by ViralBShah** [comment]
That will shift the burden on the julia side to lock before entering. I guess that's not too bad.

**Comment by staticfloat** [comment]
What function are you considering calling on multiple threads?

**Comment by ViralBShah** [comment]
None - but I don't know what users will do.
